name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: |
          npm run run:SystemClubbing
          # Define paths
          ALLURE_RESULTS_DIR="allure-results"
          ALLURE_HISTORY_DIR="allure-history"

          # Check if allure-results directory exists
          if [ -d "$ALLURE_RESULTS_DIR" ]; then
              # Move allure-results directory to allure-history directory
              mv "$ALLURE_RESULTS_DIR" "$ALLURE_HISTORY_DIR"
              echo "Allure report stored successfully."
          else
              echo "No Allure results found. Report not stored."
          fi

      - name: Get Allure history
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: allure-history

      - name: Allure Report Action
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish_branch: gh-pages
          publish_dir: allure-history
