name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Install dependencies
        run: npm install

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Run Cypress tests
        id: cypress-tests
        run: npm run run:SystemClubbing

      - name: Generate Allure Report
        run: allure generate allure-results --clean -o allure-report

      - name: Deploy report page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          user_name: 'github-actions[bot]'
          user_email: 'pratik.jain@blitzscale.co'
