name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Install dependencies
        run: npm install

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Run Cypress tests
        id: cypress-tests
        run: npm run run:SystemClubbing

      - name: Generate Allure Report
        run: npm run allure:report

      - name: Deploy report page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          user_name: 'github-actions[bot]'
          user_email: 'pratik.jain@blitzscale.co'

      - name: Extract Allure report link
        id: extract-report-link
        run: |
          REPORT_URL=$(cat allure-report/report-export.json | jq -r '.[0].url')
          echo "::set-output name=url::$REPORT_URL"

      - name: slack-send
  # You may pin to the exact commit or the version.
  # uses: slackapi/slack-github-action@6c661ce58804a1a20f6dc5fbee7f0381b469e001
        uses: slackapi/slack-github-action@v1.25.0
        with:
          slack_channel: "#cypress-orders-alerts"
          slack_message: "Allure report is available at ${{ steps.extract-report-link.outputs.url }}"
          slack_webhook_url: "https://hooks.slack.com/services/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"
