name: Cypress Workflow

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Set up Node.js
        run : npm i

      - name: Install pdf2html and pdf-parse
        run: npm install pdf2html pdf-parse

      -  name: Install pdf2html 
         run: npm install pdf2html 

      - name: Install pdf-parse
        run: npm install pdf-parse

      - name: Cypress run
        uses: cypress-io/github-action@v5

     
