name: Cypress tests

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '10.5.0'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run run:SystemClubbing
